TUPLE_POSITIVITY_FIXES = (
    "SIMPLE", "NASA", "HAS"
)

TUPLE_FLUX_SPLITTING = (
    "ROE", "CLLF", "LLF", "CLF"
)

TUPLE_FROZEN_STATE = (
    "ARITHMETIC", "ROE"
)

TUPLE_RECONSTRUCTION_VARIABLES = (
    "PRIMITIVE", "CONSERVATIVE",
    "CHAR-PRIMITIVE", "CHAR-CONSERVATIVE"
)

TUPLE_GEOMETRIC_SOURCES = (
    "AXISYMMETRIC", "CYLINDRICAL", "SPHERICAL"
)
