TUPLE_LEVELSET_MODELS = (
    "FLUID-FLUID",
    "FLUID-SOLID"
)

TUPLE_NORMAL_COMPUTATION_METHOD = (
    "FINITEDIFFERENCE",
    "APERTUREBASED"
)

TUPLE_VISCOUS_FLUX_METHOD = (
    "MEYER"
)

TUPLE_INTERFACE_RECONSTRUCTION_METHOD = (
    "MARCHINGSQUARES",
    "NEURALNETWORK" 
)

TUPLE_SOLID_COUPLINGS = (
    "ONE-WAY",
    "TWO-WAY"
)