TUPLE_LEVELSET_MODELS = (
    "FLUID-FLUID", "FLUID-SOLID-STATIC",
    "FLUID-SOLID-DYNAMIC", "FLUID-SOLID-DYNAMIC-COUPLED"
)

TUPLE_MIXER_TYPE = (
    "LAUER"
)

TUPLE_SOLID_TEMPERATURE_MODELS = (
    "CUSTOM", "ADIABATIC"
)

TUPLE_VISCOUS_FLUX_METHOD = (
    "JAXFLUIDS", "MEYER"
)