from typing import Dict

from jaxfluids.stencils.spatial_reconstruction import SpatialReconstruction

from jaxfluids.stencils.reconstruction.shock_capturing import SHOCK_CAPTURING_DICT
from jaxfluids.stencils.reconstruction.central import CENTRAL_RECONSTRUCTION_DICT
