TUPLE_DIFFUSE_INTERFACE_MODELS = (
    "5EQM"
)

TUPLE_THINC_TYPES = (
    "DENG", "SHYUE", "RHOTHINC", "PRIMITIVE"
)

TUPLE_INTERFACE_PROJECTION = (
    "CONST", "NORM_1", "NORM_2"
)

TUPLE_INTERFACE_TREATMENT = (
    "DENG", "SHYUE", "RHOTHINC", "PRIMITIVE", "NONE"
)

TUPLE_VOLUME_FRACTION_TRANSFORMATION = (
    "NONE", "SMOOTHING", "SIGNED-DISTANCE"
)

TUPLE_DIFFUSION_SHARPENING_MODELS = (
    "CDI", "ACDI", "MODELB", "MODELC", "MODELD"
)

TUPLE_DIFFUSION_SHARPENING_DENSITY_MODELS = (
    "INCOMPRESSIBLE", "COMPRESSIBLE"
)

TUPLE_MOBILITY_MODELS = (
    "OPT1", "OPT2", "OPT3"
)

TUPLE_SURFACE_TENSION_KERNEL = (
    "QUADRATIC"
)